language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "12"
script:
  - yarn test && yarn build
after_success:
  - yarn report-coverage
